export default {
  checkingLocal: "检查本地保存状态",
  checkingRemote: "检查网盘修改",
  checkingUpdates: "检查远端更新",
  checkedUpdates: "已检查远端更新，尚未上传或下载内容",
  checkIncomplete: "未完成远端检查，当前显示上次检查记录",
  firstPreview: "首次同步预览",
  firstPreviewSummary:
    "本机 {local} 项，网盘 {remote} 项；按作品身份合并，同名的不同作品会分别保留。",
  confirmFirst: "确认首次同步内容",
  readingChanges: "读取变化：{title}",
  uploading: "上传到远端：{title}",
  downloading: "下载到本机：{title}",
  transferFailed: "该作品正在写入、已发生新修改或结构不兼容，请保存后重试。",
  validationFailed: "作品结构不兼容或存在缺失引用，请检查相关文件后重试。",
  syncSummary: "已上传 {uploaded} 项，已下载 {downloaded} 项",
  partialSummary:
    "已上传 {uploaded} 项，已下载 {downloaded} 项，{issues} 项未完成",
  noChanges: "检查完成，没有需要传输的修改",
  previewIncomplete: "初始化预览未完成，本机数据保持不变",
  initializationFailed: "初始化未完成，请检查提示后重试",
  cancelled: "同步已取消，已保存内容不受影响",
  syncFailed: "同步未完成，请重试",
  restored: "已恢复到本机，下次手动同步时上传",
  checkingSource: "检查初始化来源",
  downloadingSource: "下载并校验：{title}",
  sourceReady: "远端数据已下载并校验，请确认后初始化本机",
  recheckingRemote: "再次核对远端版本",
  replacingLocal: "正在安全替换本机数据，请稍候",
  initialized: "本机已初始化，已与“{device}”本次上传的 {count} 项内容一致",
  directionConflict: "本机和远端都有修改，请先合并两端修改；本次未覆盖任一端。",
  mergeConflict: "两端修改需要确认，其他作品将继续同步。",
  deletionPending: "另一端删除了内容，请确认后应用。",
  noLocalVersion: "本机没有可采用的版本，未将缺失内容作为删除同步。",
  remoteDiverged:
    "多台远端设备的版本仍不一致，请先在来源设备同步，或采用本地版本。",
  noRemoteVersion: "远端没有可采用的版本，请先在另一端上传后重试。",
  missingDependencies: "绑定的资料尚未就绪，请加入对应资料库并处理其同步事项。",
  referencedResource:
    "此资料仍被 {sources} 引用，请先解除引用，或将引用方一并确认同步删除。",
  remoteInvalid: "网盘中的作品未通过完整性校验，本次未改动该作品。",
  localInvalid: "此作品目录不可读或结构不兼容，本次不参与同步。",
  beforeRestore: "恢复历史前的版本",
  beforeSync: "同步前的版本",
  receivedChanges: "从 {device} 取回修改",
  receivedRemote: "从网盘取回修改",
  preparedUpload: "已准备上传本机修改",
  uploaded: "本机修改已同步到网盘",
  legacyHistory: "同步历史记录"
} as const;
